[package]
name = "hCRIU"
version = "0.1.0"
edition = "2024"

[dependencies]
bytesize = "2.0.1"
clap = { version = "4.5.38", features = ["derive"] }
humantime = "2.2.0"
rust-criu = "0.4.0"
which = "7.0.3"
